sudo: false

language: node_js

node_js:
  - 14

cache:
  directories:
    # I think it defaults to this:
    - node_modules
    # Default if "npm ci" were the script, but non-empty, so include it explicitly:
    - ~/.npm

addons:
  apt:
    packages:
      - xvfb
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install

before_script:
  - npm run install:avivator

script:
  - ./test.sh
