packages:
  - sites/**
  - packages/**

catalog:
  "@deck.gl/core": ~9.2.2
  "@deck.gl/extensions": ~9.2.2
  "@deck.gl/geo-layers": ~9.2.2
  "@deck.gl/layers": ~9.2.2
  "@deck.gl/mesh-layers": ~9.2.2
  "@deck.gl/react": ~9.2.2
  "@deck.gl/test-utils": ~9.2.2
  "@deck.gl/widgets": ~9.2.2
  "@luma.gl/constants": ~9.2.4
  "@luma.gl/core": ~9.2.4
  "@luma.gl/engine": ~9.2.4
  "@luma.gl/shadertools": ~9.2.4
  "@luma.gl/test-utils": ~9.2.4
  "@luma.gl/webgl": ~9.2.4
  "@luma.gl/webgpu": ~9.2.4
  "@math.gl/core": ^4.0.1
  "@math.gl/culling": ^4.0.1
  "math.gl": ^4.0.1
  "react": ^16.8.0 || ^17.0.0 || ^18.0.0 || ^19.0.0
