packages:
  - sites/**
  - packages/**

catalog:
  "@deck.gl/core": ~8.8.27
  "@deck.gl/extensions": ~8.8.27
  "@deck.gl/geo-layers": ~8.8.27
  "@deck.gl/layers": ~8.8.27
  "@deck.gl/mesh-layers": ~8.8.27
  "@deck.gl/react": ~8.8.27
  "@deck.gl/test-utils": ~8.8.27
  "@luma.gl/constants": ~8.5.21
  "@luma.gl/core": ~8.5.21
  "@luma.gl/engine": ~8.5.21
  "@luma.gl/shadertools": ~8.5.21
  "@luma.gl/test-utils": ~8.5.21
  "@luma.gl/webgl": ~8.5.21
  "@math.gl/core": ^3.5.7
  "@math.gl/culling": ^3.5.7
  "math.gl": ^3.5.7
  "react": ^16.8.0 || ^17.0.0
