packages:
  - sites/**
  - packages/**

catalog:
  "@deck.gl/core": ~9.0.33
  "@deck.gl/extensions": ~9.0.33
  "@deck.gl/geo-layers": ~9.0.33
  "@deck.gl/layers": ~9.0.33
  "@deck.gl/mesh-layers": ~9.0.33
  "@deck.gl/react": ~9.0.33
  "@deck.gl/test-utils": ~9.0.33
  "@luma.gl/constants": ~9.0.27
  "@luma.gl/core": ~9.0.27
  "@luma.gl/engine": ~9.0.27
  "@luma.gl/shadertools": ~9.0.27
  "@luma.gl/test-utils": ~9.0.27
  "@luma.gl/webgl": ~9.0.27
  "@math.gl/core": ^4.0.1
  "@math.gl/culling": ^4.0.1
  "math.gl": ^4.0.1
  "react": ^16.8.0 || ^17.0.0 || ^18.0.0
