import { FetchStore } from 'zarrita';
import { FileStore } from './lib/storage';
import { getRootPrefix } from './lib/utils';

import { load as loadBioformats } from './bioformats-zarr';
import { load as loadOme } from './ome-zarr';

interface ZarrOptions {
  fetchOptions: RequestInit;
}

/**
 * Opens root of multiscale OME-Zarr via URL.
 *
 * @param source url
 * @param options
 * @return data source and associated OME-Zarr metadata.
 */
export async function loadOmeZarr(
  source: string,
  options: Partial<ZarrOptions & { type: 'multiscales' }> = {}
) {
  const store = new FetchStore(source, options.fetchOptions);

  if (options?.type !== 'multiscales') {
    throw Error('Only multiscale OME-Zarr is supported.');
  }

  return loadOme(store);
}

/**
 * Internal helper to load bioformats zarr with specified metadata and zarr directory paths.
 */
async function _DEPRECATED_loadBioformatsZarrWithPaths(
  source: string | (File & { path: string })[],
  metadataPath: string,
  zarrDir: string,
  options: Partial<ZarrOptions> = {}
) {
  if (typeof source === 'string') {
    const url = source.endsWith('/') ? source.slice(0, -1) : source;
    const store = new FetchStore(`${url}/${zarrDir}`, options.fetchOptions);
    const xmlSource = await fetch(
      `${url}/${metadataPath}`,
      options.fetchOptions
    );
    if (!xmlSource.ok) {
      throw Error('No OME-XML metadata found for store.');
    }
    return loadBioformats(store, xmlSource);
  }

  /*
   * You can't randomly access files from a directory by path name
   * without the Native File System API, so we need to get objects for _all_
   * the files right away for Zarr. This is unfortunate because we need to iterate
   * over all File objects and create an in-memory index.
   *
   * fMap is simple key-value mapping from 'some/file/path' -> File
   */
  const fMap: Map<string, File> = new Map();

  let xmlFile: File | undefined;
  for (const file of source) {
    if (file.name === metadataPath) {
      xmlFile = file;
    } else {
      fMap.set(file.path, file);
    }
  }

  if (!xmlFile) {
    throw Error('No OME-XML metadata found for store.');
  }
  const store = new FileStore(fMap, getRootPrefix(source, zarrDir));
  return loadBioformats(store, xmlFile);
}

/**
 * DEPRECATED: This function is designed to load Zarr data generated by an old version of bioformats2raw
 * (circa 2022 and pre-v0.5.0). You are probably looking for the loadOmeZarr function instead,
 * which is designed to load modern OME-Zarr data following the OME-NGFF specifications,
 * which is also the current (as of 2026) bioformats2raw output format.
 *
 * OLD DESCRIPTION: Opens root directory generated via
 * `bioformats2raw --file_type=zarr`.
 * Uses OME-XML metadata, and assumes first image.
 * This function is the zarr-equivalent to using loadOmeTiff.
 *
 * Supports both METADATA.ome.xml and OME/METADATA.ome.xml
 *
 * @param source url
 * @param options
 * @return data source and associated OMEXML metadata.
 */
export async function DEPRECATED_loadBioformatsZarr(
  source: string | (File & { path: string })[],
  options: Partial<ZarrOptions> = {}
) {
  // Try both old and new formats in parallel, return the first successful result
  // Old format: METADATA.ome.xml at root, data.zarr/ directory
  // New format: OME/METADATA.ome.xml, root zarr directory
  return Promise.any([
    _DEPRECATED_loadBioformatsZarrWithPaths(
      source,
      'METADATA.ome.xml',
      'data.zarr',
      options
    ),
    _DEPRECATED_loadBioformatsZarrWithPaths(
      source,
      'OME/METADATA.ome.xml',
      '',
      options
    )
  ]);
}
